import { GameMode } from "../enums/game-mode";
import { MultiScoringType } from "../enums/multi-scoring-type";
import { MultiTeamType } from "../enums/multi-team-type";
import { Mods } from "../enums/mods";

/**
 * Multi game info class
 */
export type MultiGame = {
  /**
   * Match ID [alias: gameId]
   */
  id: number;
  /**
   * Match id [alias of: id]
   */
  gameId: number;
  /**
   * Game start time
   */
  startTime: Date;
  /**
   * Game end time
   */
  endTime: Date;
  /**
   * ID of beatmap played
   */
  beatmapId: number;
  /**
   * Game mode the beatmap was played in
   */
  playMode: GameMode;
  /**
   * Winning condition
   */
  scoringType: MultiScoringType;
  /**
   * Team type
   */
  teamType: MultiTeamType;
  /**
   * Bitwise flag of mods used generated by the C#
   */
  mods: Mods;
  /**
   * Scores in the game
   */
  scores: MultiScore[];
};

class Foo implements MultiGame {}
